// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-ODmLZy9JKIqa2kuW_-qbtFgz6iC49w',
    appId: '1:253825748499:web:0e74411dbe0a0d8f5fb9e6',
    messagingSenderId: '253825748499',
    projectId: 'gestaofinanceiraflutter',
    authDomain: 'gestaofinanceiraflutter.firebaseapp.com',
    storageBucket: 'gestaofinanceiraflutter.firebasestorage.app',
    measurementId: 'G-6VB59JLE0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-hXUajitwNMlcTdJRBgnJXPMBkdXHh1U',
    appId: '1:253825748499:android:e0196403ff440de55fb9e6',
    messagingSenderId: '253825748499',
    projectId: 'gestaofinanceiraflutter',
    storageBucket: 'gestaofinanceiraflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3bfySruO_1FoqQWux6XjFsKymWbpsDOM',
    appId: '1:253825748499:ios:d10647502c33d2845fb9e6',
    messagingSenderId: '253825748499',
    projectId: 'gestaofinanceiraflutter',
    storageBucket: 'gestaofinanceiraflutter.firebasestorage.app',
    iosBundleId: 'com.example.financehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3bfySruO_1FoqQWux6XjFsKymWbpsDOM',
    appId: '1:253825748499:ios:d10647502c33d2845fb9e6',
    messagingSenderId: '253825748499',
    projectId: 'gestaofinanceiraflutter',
    storageBucket: 'gestaofinanceiraflutter.firebasestorage.app',
    iosBundleId: 'com.example.financehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL-ODmLZy9JKIqa2kuW_-qbtFgz6iC49w',
    appId: '1:253825748499:web:7c7cded13a0deb895fb9e6',
    messagingSenderId: '253825748499',
    projectId: 'gestaofinanceiraflutter',
    authDomain: 'gestaofinanceiraflutter.firebaseapp.com',
    storageBucket: 'gestaofinanceiraflutter.firebasestorage.app',
    measurementId: 'G-1NC88WJYJC',
  );
}
